name: Node CI

on: [push]
      
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    
    ## NodeJS-Build
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    
    ## Webjar-Build
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    ## Deploy
    - name: Deploy package
      if: success() && (github.ref == 'master' || github.ref == 'feature/build-webjar')
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/levigo -Dtoken=GH_TOKEN
      
